# Generated by Django 5.2.15 on 2026-06-10 01:05

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('data_bori', models.DateField(blank=True, null=True)),
                ('filho_iniciado', models.BooleanField(default=False, verbose_name='Filho Iniciado?')),
                ('data_iniciacao', models.DateField(blank=True, null=True, verbose_name='Data da Iniciação')),
                ('ordem_posto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ordem/Posto')),
                ('orixa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Orixá')),
                ('orunko', models.CharField(blank=True, max_length=100, null=True, verbose_name='Orunkó')),
                ('nome_ere', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Erê')),
                ('madrinha_padrinho', models.CharField(blank=True, max_length=150, null=True, verbose_name='Madrinha/Padrinho')),
                ('mae_pai_pequeno', models.CharField(blank=True, max_length=150, null=True, verbose_name='Mãe/Pai Pequeno')),
                ('eh_administrador', models.BooleanField(default=False, verbose_name='É administrador?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Filho',
                'verbose_name_plural': 'Filhos',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
