# Generated by Django 5.2.15 on 2026-06-10 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField(help_text='Use o dia 1 do mês correspondente')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Pendente'), ('atrasado', 'Atrasado')], default='pendente', max_length=9)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/')),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('filho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensalidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensalidade',
                'verbose_name_plural': 'Mensalidades',
            },
        ),
    ]
