# Generated by Django 5.2.15 on 2026-06-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensalidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalidade',
            name='status',
            field=models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Pendente'), ('atrasado', 'Atrasado'), ('recusado', 'Recusado')], default='pendente', max_length=9),
        ),
    ]
