# Generated by Django 5.2.15 on 2026-06-10 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensalidades', '0002_alter_mensalidade_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IsentoMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField(help_text='Use o dia 1 do mês correspondente')),
                ('motivo', models.TextField(blank=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isencoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('filho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isencoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Isenção de Mês',
                'verbose_name_plural': 'Isenções de Mês',
                'unique_together': {('filho', 'mes_referencia')},
            },
        ),
    ]
